/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author MADICAP
 */
public class Cliente extends javax.swing.JFrame {

    /**
     * Creates new form Cliente
     */
    public Cliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Principal = new javax.swing.JTabbedPane();
        Compras = new javax.swing.JPanel();
        Maestros1 = new javax.swing.JPanel();
        PestanaMaestros1 = new javax.swing.JTabbedPane();
        comprasRevisionFactura1 = new Vista.ComprasRevisionFactura();
        comprasRegistroCompras1 = new Vista.ComprasRegistroCompras();
        comprasSolicitudes1 = new Vista.ComprasSolicitudes();
        jLabel131 = new javax.swing.JLabel();
        Informes = new javax.swing.JPanel();
        PestanaMaestros2 = new javax.swing.JTabbedPane();
        informeVentas1 = new Vista.InformeVentas();
        informeInventario1 = new Vista.InformeInventario();
        informeClientes1 = new Vista.InformeClientes();
        informeDevolucionYCambio1 = new Vista.InformeDevolucionYCambio();
        jLabel122 = new javax.swing.JLabel();
        Maestros = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PestanaMaestros = new javax.swing.JTabbedPane();
        maestroCategoria1 = new Vista.MaestroCategoria();
        maestroCategoriaArticulo1 = new Vista.MaestroCategoriaArticulo();
        maestroBanco1 = new Vista.MaestroBanco();
        maestroComuna1 = new Vista.MaestroComuna();
        maestroProveedor1 = new Vista.MaestroProveedor();
        maestroRRSS1 = new Vista.MaestroRRSS();
        maestroUsuario1 = new Vista.MaestroUsuario();
        jScrollPane2 = new javax.swing.JScrollPane();
        maestroCliente1 = new Vista.MaestroCliente();
        jScrollPane3 = new javax.swing.JScrollPane();
        maestroPack2 = new Vista.MaestroPack();
        jScrollPane4 = new javax.swing.JScrollPane();
        maestroArticulo2 = new Vista.MaestroArticulo();
        Venta = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        ventasVenta1 = new Vista.VentasVenta();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        ventasConfirmacion1 = new Vista.VentasConfirmacion();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        ventasListaDestinos1 = new Vista.VentasListaDestinos();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PestanaMaestros1.setMinimumSize(new java.awt.Dimension(128, 60));
        PestanaMaestros1.setPreferredSize(new java.awt.Dimension(912, 590));
        PestanaMaestros1.addTab("Revision de facturas", comprasRevisionFactura1);
        PestanaMaestros1.addTab("Registro de compras", comprasRegistroCompras1);
        PestanaMaestros1.addTab("Solicitudes de pedidos", comprasSolicitudes1);

        jLabel131.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel131.setText("DREAM GIFTS");

        javax.swing.GroupLayout Maestros1Layout = new javax.swing.GroupLayout(Maestros1);
        Maestros1.setLayout(Maestros1Layout);
        Maestros1Layout.setHorizontalGroup(
            Maestros1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Maestros1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PestanaMaestros1, javax.swing.GroupLayout.PREFERRED_SIZE, 912, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Maestros1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel131)
                .addGap(347, 347, 347))
        );
        Maestros1Layout.setVerticalGroup(
            Maestros1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Maestros1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel131)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PestanaMaestros1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout ComprasLayout = new javax.swing.GroupLayout(Compras);
        Compras.setLayout(ComprasLayout);
        ComprasLayout.setHorizontalGroup(
            ComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1131, Short.MAX_VALUE)
            .addGroup(ComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ComprasLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Maestros1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        ComprasLayout.setVerticalGroup(
            ComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 692, Short.MAX_VALUE)
            .addGroup(ComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ComprasLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Maestros1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        Principal.addTab("Compras", Compras);

        PestanaMaestros2.setMinimumSize(new java.awt.Dimension(128, 60));
        PestanaMaestros2.setPreferredSize(new java.awt.Dimension(912, 590));
        PestanaMaestros2.addTab("Informe ventas", informeVentas1);
        PestanaMaestros2.addTab("Informe inventario", informeInventario1);
        PestanaMaestros2.addTab("Informe clientes", informeClientes1);
        PestanaMaestros2.addTab("Informe Dev. & Cambios", informeDevolucionYCambio1);

        jLabel122.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel122.setText("DREAM GIFTS");

        javax.swing.GroupLayout InformesLayout = new javax.swing.GroupLayout(Informes);
        Informes.setLayout(InformesLayout);
        InformesLayout.setHorizontalGroup(
            InformesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InformesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PestanaMaestros2, javax.swing.GroupLayout.PREFERRED_SIZE, 912, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InformesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel122)
                .addGap(352, 352, 352))
        );
        InformesLayout.setVerticalGroup(
            InformesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InformesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel122)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PestanaMaestros2, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );

        Principal.addTab("Informes", Informes);

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel23.setText("DREAM GIFTS");

        PestanaMaestros.setMinimumSize(new java.awt.Dimension(128, 60));
        PestanaMaestros.setPreferredSize(new java.awt.Dimension(912, 590));
        PestanaMaestros.addTab("Categoria venta", maestroCategoria1);
        PestanaMaestros.addTab("Categoria articulo", maestroCategoriaArticulo1);
        PestanaMaestros.addTab("Banco", maestroBanco1);
        PestanaMaestros.addTab("Comuna", maestroComuna1);
        PestanaMaestros.addTab("Proveedor", maestroProveedor1);
        PestanaMaestros.addTab("RRSS", maestroRRSS1);
        PestanaMaestros.addTab("Usuario", maestroUsuario1);

        jScrollPane2.setViewportView(maestroCliente1);

        PestanaMaestros.addTab("Cliente", jScrollPane2);

        jScrollPane3.setViewportView(maestroPack2);

        PestanaMaestros.addTab("Pack", jScrollPane3);

        jScrollPane4.setViewportView(maestroArticulo2);

        PestanaMaestros.addTab("Articulo", jScrollPane4);

        jScrollPane1.setViewportView(PestanaMaestros);

        javax.swing.GroupLayout MaestrosLayout = new javax.swing.GroupLayout(Maestros);
        Maestros.setLayout(MaestrosLayout);
        MaestrosLayout.setHorizontalGroup(
            MaestrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MaestrosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel23)
                .addGap(386, 386, 386))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MaestrosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        MaestrosLayout.setVerticalGroup(
            MaestrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MaestrosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Principal.addTab("Maestros", Maestros);

        jLabel50.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel50.setText("DREAM GIFTS");

        jTabbedPane1.addTab("Nueva venta", ventasVenta1);

        jScrollPane5.setViewportView(ventasConfirmacion1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 1106, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Confirmar pago", jPanel1);

        jScrollPane6.setViewportView(ventasListaDestinos1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 1106, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Ventas a despachar", jPanel2);

        javax.swing.GroupLayout VentaLayout = new javax.swing.GroupLayout(Venta);
        Venta.setLayout(VentaLayout);
        VentaLayout.setHorizontalGroup(
            VentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(VentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(VentaLayout.createSequentialGroup()
                        .addComponent(jLabel50)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        VentaLayout.setVerticalGroup(
            VentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel50)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1))
        );

        Principal.addTab("Ventas", Venta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Principal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Principal, javax.swing.GroupLayout.PREFERRED_SIZE, 633, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Compras;
    private javax.swing.JPanel Informes;
    private javax.swing.JPanel Maestros;
    private javax.swing.JPanel Maestros1;
    private javax.swing.JTabbedPane PestanaMaestros;
    private javax.swing.JTabbedPane PestanaMaestros1;
    private javax.swing.JTabbedPane PestanaMaestros2;
    private javax.swing.JTabbedPane Principal;
    private javax.swing.JPanel Venta;
    private Vista.ComprasRegistroCompras comprasRegistroCompras1;
    private Vista.ComprasRevisionFactura comprasRevisionFactura1;
    private Vista.ComprasSolicitudes comprasSolicitudes1;
    private Vista.InformeClientes informeClientes1;
    private Vista.InformeDevolucionYCambio informeDevolucionYCambio1;
    private Vista.InformeInventario informeInventario1;
    private Vista.InformeVentas informeVentas1;
    private javax.swing.JLabel jLabel122;
    private javax.swing.JLabel jLabel131;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private Vista.MaestroArticulo maestroArticulo2;
    private Vista.MaestroBanco maestroBanco1;
    private Vista.MaestroCategoria maestroCategoria1;
    private Vista.MaestroCategoriaArticulo maestroCategoriaArticulo1;
    private Vista.MaestroCliente maestroCliente1;
    private Vista.MaestroComuna maestroComuna1;
    private Vista.MaestroPack maestroPack2;
    private Vista.MaestroProveedor maestroProveedor1;
    private Vista.MaestroRRSS maestroRRSS1;
    private Vista.MaestroUsuario maestroUsuario1;
    private Vista.VentasConfirmacion ventasConfirmacion1;
    private Vista.VentasListaDestinos ventasListaDestinos1;
    private Vista.VentasVenta ventasVenta1;
    // End of variables declaration//GEN-END:variables
}
