/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the ed    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
itor.
 */
package Vista;

import Controlador.ControladorArticulo;
import Controlador.ControladorCategoriaArticulo;
import Modelo.Articulo;
import Modelo.CategoriaArticulo;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.Enumeration;
import javax.swing.ButtonGroup;
import javax.swing.DefaultCellEditor;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author MADICAP
 */
public class MaestroArticulo extends javax.swing.JPanel {

    /**
     * Creates new form MaestroArticulo
     */
    private ControladorCategoriaArticulo cCatArticulo = new ControladorCategoriaArticulo();
    private ControladorArticulo cArticulo= new ControladorArticulo();
    private ButtonGroup btnGroup;
    public MaestroArticulo() {
        initComponents();
        LlenarComboBox();
        LlenarTabla();
        btnConfirmarEdicion.setVisible(false);
    }
    public void LlenarComboBox()
    {
        ArrayList<CategoriaArticulo> categorias = cCatArticulo.ListarCategorias();
        String[] categoriaArray = new String[categorias.size()];
        DefaultComboBoxModel dml= new DefaultComboBoxModel();
        for (int i = 0; i < categorias.size(); i++) {
          dml.addElement(categorias.get(i).getCatNombre());
       }
        cbxCategoriaArticulo.setModel(dml);
    }
    
    
    private void LlenarTabla() {
        ArrayList<Articulo> articulos = cArticulo.ListarArticulos();
        Object matriz[][]= new Object[articulos.size()][9];
        btnGroup = new ButtonGroup();
        for (int i = 0; i < articulos.size(); i++) {
            matriz[i][0]= articulos.get(i).getArtIdArticulo();
            matriz[i][1]= articulos.get(i).getArtDescripcion();
            matriz[i][2]= articulos.get(i).getCategoriaArticuloCategoriaArticulo().getCatNombre();
            matriz[i][3]= articulos.get(i).getArtStock();
            if(articulos.get(i).getArtFechaVencimiento() != null){
            Date date = articulos.get(i).getArtFechaVencimiento();
            DateFormat dateFormat = new SimpleDateFormat("dd/MM/YYYY");  
            String strDate = dateFormat.format(date);  
            matriz[i][4]=strDate;
            }
            else {
                matriz[i][4]="S/N";
            }
            matriz[i][5]=articulos.get(i).getArtMarca();
            matriz[i][6]=articulos.get(i).getArtPrecio();
            matriz[i][7]=articulos.get(i).Habilitado();
            JRadioButton btn = new JRadioButton();
            btn.setName(Integer.toString(articulos.get(i).getArtIdArticulo()));
            btn.addActionListener(new ActionListener() {
                 @Override
                 public void actionPerformed(ActionEvent e) {
                    if(btn.isSelected())
                    {
                        tblArticulo.repaint();
                    }
                 }
             });
            matriz[i][8]= btn;
            btnGroup.add((JRadioButton)matriz[i][8]);
        }
        tblArticulo.setModel(new javax.swing.table.DefaultTableModel(matriz, new String [] {
                "Código", "Artículo", "Categoría Artículo", "Unidades", "Fecha De Vencimiento", "Marca","Precio", "Habilitado", "Acción"})
           {
                boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false,false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }        
           });
                
                
        String accion = tblArticulo.getColumnName(8);
        tblArticulo.getColumn(accion).setCellRenderer(new RadioButtonRenderer());
        tblArticulo.getColumn(accion).setCellEditor(new RadioButtonEditor(new JCheckBox()));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SubArticulos = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtPrecio = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        cbxCategoriaArticulo = new javax.swing.JComboBox<>();
        txtFecha = new com.toedter.calendar.JDateChooser();
        btnConfirmarEdicion = new javax.swing.JButton();
        cbxSinVencimiento = new javax.swing.JCheckBox();
        jLabel42 = new javax.swing.JLabel();
        txtUnidades = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblArticulo = new javax.swing.JTable();
        btnDesactivar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jLabel46 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();

        jPanel20.setBackground(new java.awt.Color(255, 255, 255));
        jPanel20.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Artículos"));

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel40.setText("Nombre Artículo");

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel41.setText("Fecha De Vencimiento");

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel43.setText("Marca");

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel44.setText("Unidades");

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel45.setText("Categoría Artículo");

        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        cbxCategoriaArticulo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnConfirmarEdicion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnConfirmarEdicion.setText("Confirmar edicion");
        btnConfirmarEdicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarEdicionActionPerformed(evt);
            }
        });

        cbxSinVencimiento.setText("Articulo sin fecha de vencimiento");
        cbxSinVencimiento.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if(cbxSinVencimiento.isSelected())
                {
                    txtFecha.setDate(null);
                    txtFecha.setEnabled(false);
                }
                else
                {
                    txtFecha.setDate(null);
                    txtFecha.setEnabled(true);
                }
            }
        });

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel42.setText("Precio");

        jLabel47.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel47.setText("$");

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel40)
                    .addComponent(jLabel44, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel43, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnConfirmarEdicion, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel20Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel45)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbxCategoriaArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel20Layout.createSequentialGroup()
                                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel42)
                                    .addComponent(jLabel41))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbxSinVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel20Layout.createSequentialGroup()
                                        .addComponent(jLabel47)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(68, 68, 68))
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel40)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel44)
                            .addComponent(txtUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel20Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel20Layout.createSequentialGroup()
                                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel45)
                                    .addComponent(cbxCategoriaArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel41))
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxSinVencimiento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel42)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel47))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar)
                    .addComponent(btnConfirmarEdicion))
                .addGap(27, 27, 27))
        );

        jPanel21.setBackground(new java.awt.Color(255, 255, 255));

        tblArticulo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Artículo", "Categoría Artículo", "Unidades", "Fecha De Vencimiento", "Marca", "Precio", "Habilitado", "Acción"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tblArticulo);

        btnDesactivar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDesactivar.setText("Activar/Desactivar");
        btnDesactivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesactivarActionPerformed(evt);
            }
        });

        btnEditar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnDesactivar)
                .addContainerGap())
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDesactivar)
                    .addComponent(btnEditar))
                .addContainerGap())
        );

        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel46.setText("Artículos");

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout SubArticulosLayout = new javax.swing.GroupLayout(SubArticulos);
        SubArticulos.setLayout(SubArticulosLayout);
        SubArticulosLayout.setHorizontalGroup(
            SubArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubArticulosLayout.createSequentialGroup()
                .addGroup(SubArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SubArticulosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(SubArticulosLayout.createSequentialGroup()
                        .addGap(394, 394, 394)
                        .addComponent(jLabel46)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        SubArticulosLayout.setVerticalGroup(
            SubArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubArticulosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(SubArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel46)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 907, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(SubArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 546, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(SubArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        String nombre,categoria,marca;
        int unidades,id,precio;
        id=cArticulo.CountClientes();
        Date fecha;
        precio= Integer.parseInt(txtPrecio.getText());
        nombre=txtNombre.getText();
        unidades = Integer.parseInt(txtUnidades.getText());
        marca = txtMarca.getText();
        categoria = (String) cbxCategoriaArticulo.getSelectedItem();
        Articulo articulo= new Articulo();
        articulo.setArtDescripcion(nombre);
        if(cbxSinVencimiento.isSelected())
        {
            fecha = null;
        }
        else {
            fecha = txtFecha.getCalendar().getTime();
        }
        articulo.setArtFechaVencimiento(fecha);
        articulo.setArtIdArticulo(id);
        articulo.setArtPrecio(precio);
        articulo.setArtMarca(marca);
        articulo.setArtStock(unidades);
        articulo.setArtInhabilitado((short)0);
        CategoriaArticulo cat = cCatArticulo.BuscarPorNombre(categoria);
        articulo.setCategoriaArticuloCategoriaArticulo(cat);
        cArticulo.AgregarArticulo(articulo);
        JOptionPane.showMessageDialog(SubArticulos.getParent(),"Articulo registrado","Aviso",JOptionPane.INFORMATION_MESSAGE);
        btnCancelarActionPerformed(evt);
        LlenarTabla();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        txtNombre.setText("");
        txtFecha.setDate(null);
        txtMarca.setText("");
        txtPrecio.setText("");
        txtUnidades.setText("");
        cbxSinVencimiento.setSelected(false);
        txtFecha.setEnabled(true);
        btnConfirmarEdicion.setVisible(false);
        btnGuardar.setVisible(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        Enumeration enumButtons = btnGroup.getElements();
        int id=0;       
        while(enumButtons.hasMoreElements()==true){
            JRadioButton j = (JRadioButton) enumButtons.nextElement();
            if(j.isSelected())
            {
                id=Integer.parseInt(j.getName());
            }
        }
        Articulo articulo = cArticulo.BuscarPorId(id);
        txtNombre.setText(articulo.getArtDescripcion());
        if(articulo.getArtFechaVencimiento()!=null)
        {
            txtFecha.setDate(articulo.getArtFechaVencimiento());
        }else{
            txtFecha.setEnabled(false);
            txtFecha.setDate(null);
            cbxSinVencimiento.setSelected(true);
        }
        txtMarca.setText(articulo.getArtMarca());
        txtUnidades.setText(Integer.toString(articulo.getArtStock()));
        txtPrecio.setText(Integer.toString(articulo.getArtPrecio()));
        cbxCategoriaArticulo.setSelectedIndex(articulo.getCategoriaArticuloCategoriaArticulo().getCategoriaArticulo()-1);
        btnConfirmarEdicion.setVisible(true);
        btnGuardar.setVisible(false);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnConfirmarEdicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarEdicionActionPerformed
        // TODO add your handling code here:
        Enumeration enumButtons = btnGroup.getElements();
        int id=0;
        while(enumButtons.hasMoreElements()==true){
            JRadioButton j = (JRadioButton) enumButtons.nextElement();
            if(j.isSelected())
            {
                id=Integer.parseInt(j.getName());
            }
        }
        Articulo articulo = cArticulo.BuscarPorId(id);
        String nombre,categoria,marca;
        int unidades,precio;
        Date fecha;
        nombre=txtNombre.getText();
        unidades = Integer.parseInt(txtUnidades.getText());
        precio= Integer.parseInt(txtPrecio.getText());
        marca = txtMarca.getText();
        categoria = (String) cbxCategoriaArticulo.getSelectedItem();
        articulo.setArtDescripcion(nombre);
        if(cbxSinVencimiento.isSelected())
        {
            fecha = null;
        }
        else {
            fecha = txtFecha.getCalendar().getTime();
        }
        articulo.setArtFechaVencimiento(fecha);
        articulo.setArtMarca(marca);
        articulo.setArtStock(unidades);
        articulo.setArtPrecio(precio);
        articulo.setArtInhabilitado((short)0);
        CategoriaArticulo cat = cCatArticulo.BuscarPorNombre(categoria);
        articulo.setCategoriaArticuloCategoriaArticulo(cat);
        cArticulo.EditarArticulo(articulo);
        JOptionPane.showMessageDialog(SubArticulos.getParent(),"Articulo modificado","Aviso",JOptionPane.INFORMATION_MESSAGE);
        btnCancelarActionPerformed(evt);
        LlenarTabla();
        
    }//GEN-LAST:event_btnConfirmarEdicionActionPerformed

    private void btnDesactivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesactivarActionPerformed
        // TODO add your handling code here:
         Enumeration enumButtons = btnGroup.getElements();
        int id=0;       
        while(enumButtons.hasMoreElements()==true){
            JRadioButton j = (JRadioButton) enumButtons.nextElement();
            if(j.isSelected())
            {
                id=Integer.parseInt(j.getName());
            }
        }
        Articulo articulo = cArticulo.BuscarPorId(id);
        if(articulo.Habilitado().equals("Si"))
        {
            articulo.setArtInhabilitado(Short.parseShort("1"));
            JOptionPane.showMessageDialog(SubArticulos.getParent(),"Articulo desactivado","Aviso",JOptionPane.WARNING_MESSAGE);
        }
        else{
            articulo.setArtInhabilitado(Short.parseShort("0"));
            JOptionPane.showMessageDialog(SubArticulos.getParent(),"Articulo activado","Aviso",JOptionPane.WARNING_MESSAGE);
        }     
        cArticulo.EditarArticulo(articulo);
        btnCancelarActionPerformed(evt);
        LlenarTabla();
    }//GEN-LAST:event_btnDesactivarActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        // TODO add your handling code here:
         ArrayList<Articulo> articulos = cArticulo.Busqueda(txtBuscar.getText());
         Object matriz[][]= new Object[articulos.size()][9];
        btnGroup = new ButtonGroup();
        for (int i = 0; i < articulos.size(); i++) {
            matriz[i][0]= articulos.get(i).getArtIdArticulo();
            matriz[i][1]= articulos.get(i).getArtDescripcion();
            matriz[i][2]= articulos.get(i).getCategoriaArticuloCategoriaArticulo().getCatNombre();
            matriz[i][3]= articulos.get(i).getArtStock();
            if(articulos.get(i).getArtFechaVencimiento() != null){
            Date date = articulos.get(i).getArtFechaVencimiento();
            DateFormat dateFormat = new SimpleDateFormat("dd/MM/YYYY");  
            String strDate = dateFormat.format(date);  
            matriz[i][4]=strDate;
            }
            else {
                matriz[i][4]="S/N";
            }
            matriz[i][5]=articulos.get(i).getArtMarca();
            matriz[i][6]=articulos.get(i).getArtPrecio();
            matriz[i][7]=articulos.get(i).Habilitado();
            JRadioButton btn = new JRadioButton();
            btn.setName(Integer.toString(articulos.get(i).getArtIdArticulo()));
            btn.addActionListener(new ActionListener() {
                 @Override
                 public void actionPerformed(ActionEvent e) {
                    if(btn.isSelected())
                    {
                        tblArticulo.repaint();
                    }
                 }
             });
            matriz[i][8]= btn;
            btnGroup.add((JRadioButton)matriz[i][8]);
        }
        tblArticulo.setModel(new javax.swing.table.DefaultTableModel(matriz, new String [] {
                "Código", "Artículo", "Categoría Artículo", "Unidades", "Fecha De Vencimiento", "Marca", "Precio", "Habilitado", "Acción"})
           {
                boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false,false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }        
           });
                
                
        String accion = tblArticulo.getColumnName(8);
        tblArticulo.getColumn(accion).setCellRenderer(new RadioButtonRenderer());
        tblArticulo.getColumn(accion).setCellEditor(new RadioButtonEditor(new JCheckBox()));
        tblArticulo.repaint();
    }//GEN-LAST:event_txtBuscarKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SubArticulos;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmarEdicion;
    private javax.swing.JButton btnDesactivar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cbxCategoriaArticulo;
    private javax.swing.JCheckBox cbxSinVencimiento;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tblArticulo;
    private javax.swing.JTextField txtBuscar;
    private com.toedter.calendar.JDateChooser txtFecha;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtUnidades;
    // End of variables declaration//GEN-END:variables
class RadioButtonRenderer implements TableCellRenderer {
   public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected,        boolean hasFocus, int row, int column) {
      if (value==null) return null;
         return (Component)value;
   }
}
class RadioButtonEditor extends DefaultCellEditor implements ItemListener {
   private JRadioButton button;
   public RadioButtonEditor(JCheckBox checkBox) {
      super(checkBox);
   }
   public Component getTableCellEditorComponent(JTable table, Object value, boolean isSelected, int row, int column) {
      if (value==null) return null;
      button = (JRadioButton)value;
      button.addItemListener(this);
      return (Component)value;
   }
   public Object getCellEditorValue() {
      button.removeItemListener(this);
      return button;
   }
   public void itemStateChanged(ItemEvent e) {
      super.fireEditingStopped();
   }
}
}

